name: Build image
on: 
  push:
    branches:
      - 'feature/**'
jobs:
  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - imagename: innovabit/artemis
            path: artemis
          - imagename: innovabit/net6sdk
            path: net/sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        env:
          IMAGENAME: ${{ matrix.imagename }}
          WORKDIR: ${{ matrix.path }}
        run: docker build -t $IMAGENAME .
        working-directory: $WORKDIR