name: Build image
on: 
  push:
    branches:
      - 'feature/**'
jobs:
  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - imagename: innovabitpe/artemis
            path: artemis
          - imagename: innovabitpe/net6sdk
            path: net/sdk
          - imagename: innovabitpe/net6runtime
            path: net/runtime
          - imagename: innovabitpe/net6aspnet
            path: net/aspnet
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        env:
          IMAGENAME: ${{ matrix.imagename }}
          WORKDIR: ${{ matrix.path }}
        run: docker build -t ${{ env.IMAGENAME }} .
        working-directory: ${{ env.WORKDIR }}