name: Build and publish image
on: 
  push:
    branches:
      - develop
jobs:
  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - imagename: innovabitpe/artemis
            path: artemis
            description: ActiveMQ Artemis image using Linux OS.
          - imagename: innovabitpe/net6sdk
            path: net/sdk
            description: Custom Net Core SDK 6.0
          - imagename: innovabitpe/net6runtime
            path: net/runtime
            description: Custom Net Core Runtime 6.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish to Docker Hub
        uses: docker/build-push-action@v2
        env:
          IMAGENAME: ${{ matrix.imagename }}
          WORKDIR: ${{ matrix.path }}
        with:
          context: ${{ env.WORKDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          push: true
          tags: ${{ env.IMAGENAME }}:latest,${{ env.IMAGENAME }}:1.0.0.${{ github.run_number }}
      - name: Update description
        uses: peter-evans/dockerhub-description@v3
        env:
          IMAGENAME: ${{ matrix.imagename }}
          WORKDIR: ${{ matrix.path }}
          DESCRIPTION: ${{ matrix.description }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ env.IMAGENAME }}
          readme-filepath: ./${{ env.WORKDIR }}/README.md
          short-description: ${{ env.DESCRIPTION }}