name: Build image
on: 
  push
jobs:
  docker-build:
    name: Build docker images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build image
        run: docker build -t innovabit/artemis .
        working-directory: artemis
